name: Deploy to GitHub Pages

# Run workflow on every push to the main branch
on:
  push:

jobs:
  deploy-to-github-pages:
    # use ubuntu-latest image to run steps on
    runs-on: ubuntu-latest
    steps:
      # uses GitHub's checkout action to checkout code from the main branch
      - uses: actions/checkout@v2

      # sets up .NET SDK 8.0.x
      - name: Setup .NET SDK 8.0.x
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: "8.0.x"

      # publishes Blazor project to the release folder
      - name: Publish .NET Project
        run: dotnet publish FrontEnd.Web/FrontEnd.Web.csproj -c Release -o release --nologo

      - name: Publish DataEditor
        run: dotnet publish DataEditor.Web/DataEditor.Web.csproj -c Release -o releasedataeditor --nologo

      - name: Copy DataEditor
        run: cp -R releasedataeditor/wwwroot release/wwwroot/dataeditor

      # changes the base-tag in index.html from '/' to 'BlazorGitHubPagesDemo' to match GitHub Pages repository subdirectory
      - name: Change base-tag in index.html from / to BlazorGitHubPagesDemo
        run: sed -i 's/<base href="\/" \/>/<base href="\/FrontEnd.Web\/" \/>/g' release/wwwroot/index.html

      # copy index.html to 404.html to serve the same file when a file is not found
      - name: copy index.html to 404.html
        run: cp release/wwwroot/index.html release/wwwroot/404.html

      # add .nojekyll file to tell GitHub pages to not treat this as a Jekyll project. (Allow files and folders starting with an underscore)
      - name: Add .nojekyll file
        run: touch release/wwwroot/.nojekyll

      # publishes wwwroot directory to GitHub Pages
      - name: Commit wwwroot to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@4.1.5
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages-${{ github.ref_name }}  # The branch the action should deploy to.
          folder: release/wwwroot # The folder the action should deploy.